name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Angular App
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          checkout: true
          path: dist/teams
          install_command: npm install
          build_command: npm run build -- --base-href=/teamprofile/
